[build]
  base = "/"
  publish = "client/build"
  command = "cd client && rm -rf node_modules && npm ci && CI=false npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
