[build]
  base = "public"
  publish = "public"
  command = "npm run netlify-build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[context.production]
  command = "npm run netlify-build"

[context.branch-deploy]
  command = "npm run netlify-build"

[context.deploy-preview]
  command = "npm run netlify-build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval';" 