[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://your-backend-url.herokuapp.com"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
