[build]
  base = "client"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://junior-joy-hr-pro.onrender.com"
  REACT_APP_SOCKET_URL = "https://junior-joy-hr-pro.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
