services:
  - type: web
    name: junior-joy-hr-pro-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://Rettey:Adhu1447@cluster0.spr2o17.mongodb.net/test
      - key: JWT_SECRET
        value: yourjwtsecretkey
      - key: FRONTEND_URL
        value: https://junior-joy-hr-pro.netlify.app
    healthCheckPath: /health 